namespace FileExplorer.Helpers;

/// A curated slice of the Segoe Fluent Icons set, offered in the "Set Icon..." workspace-tab
/// picker. Not exhaustive - just the glyphs that make sensible folder/workspace markers, each with
/// search keywords. Glyphs are the font's private-use codepoints.
public static class SegoeIconCatalog
{
    public sealed record Entry(string Glyph, string Name, string Keywords);

    public static IReadOnlyList<Entry> Icons { get; } = new List<Entry>
    {
        new("", "Home", "home house main"),
        new("", "Folder", "folder directory"),
        new("", "Folder open", "folder open"),
        new("", "Page", "page file document blank"),
        new("", "Document", "document file text"),
        new("", "Protected document", "document protected secure"),
        new("", "Flag", "flag mark priority"),
        new("", "Pin", "pin favourite"),
        new("", "Pinned", "pinned pin"),
        new("", "Star", "star favourite outline"),
        new("", "Star filled", "star favourite filled"),
        new("", "Heart", "heart love like"),
        new("", "Heart filled", "heart love filled"),
        new("", "Settings", "settings gear config options"),
        new("", "Search", "search find magnify"),
        new("", "Filter", "filter funnel"),
        new("", "Save", "save disk"),
        new("", "Copy", "copy duplicate"),
        new("", "Delete", "delete trash bin"),
        new("", "List", "list items"),
        new("", "Grid", "grid view all tiles"),
        new("", "Download", "download save incoming"),
        new("", "Upload", "upload outgoing"),
        new("", "Sync", "sync refresh update"),
        new("", "Refresh", "refresh reload"),
        new("", "Accept", "accept check done tick"),
        new("", "Checkmark", "check tick done complete"),
        new("", "Completed", "completed done check circle"),
        new("", "Contact", "contact person user profile"),
        new("", "People", "people group team users"),
        new("", "Mail", "mail email message envelope"),
        new("", "Phone", "phone call"),
        new("", "Send", "send paper plane"),
        new("", "Attach", "attach paperclip"),
        new("", "Print", "print printer"),
        new("", "Message", "message chat comment speech"),
        new("", "Globe", "globe world web internet"),
        new("", "Link", "link url chain"),
        new("", "Share", "share"),
        new("", "Calendar", "calendar date schedule"),
        new("", "Recent", "recent history clock time"),
        new("", "History", "history recent past"),
        new("", "Clock", "clock time watch"),
        new("", "Location", "location map pin place"),
        new("", "Camera", "camera photo"),
        new("", "Video", "video movie film"),
        new("", "Photo", "photo picture image"),
        new("", "Music note", "music song audio note"),
        new("", "Volume", "volume sound audio speaker"),
        new("", "Lightbulb", "lightbulb idea tip"),
        new("", "Info", "info information about"),
        new("", "Warning", "warning caution alert"),
        new("", "Error", "error info circle"),
        new("", "Shield", "shield security protect"),
        new("", "Lock", "lock secure private locked"),
        new("", "Unlock", "unlock open unlocked"),
        new("", "Permissions", "permissions key access"),
        new("", "Library", "library books collection"),
        new("", "Tag", "tag label"),
        new("", "Menu", "menu hamburger navigation"),
        new("", "Edit", "edit pencil modify"),
        new("", "Add", "add plus new"),
        new("", "Cancel", "cancel close x remove"),
        new("", "More", "more ellipsis options"),
        new("", "File explorer", "file explorer files"),
        new("", "Command prompt", "command prompt terminal console shell"),
        new("", "Code", "code source developer"),
        new("", "Bug", "bug debug issue"),
        new("", "Game", "game controller play"),
        new("", "Cloud", "cloud storage sky"),
        new("", "Shop", "shop store cart buy"),
        new("", "Shopping cart", "cart shopping basket buy"),
        new("", "Airplane", "airplane plane flight travel"),
        new("", "Car", "car vehicle drive"),
        new("", "Streaming", "streaming cast broadcast"),
        new("", "Brightness", "brightness sun light day"),
        new("", "Color", "color palette paint"),
        new("", "Work", "work briefcase job office"),
        new("", "Chart", "chart analytics graph report"),
        new("", "Analytics", "analytics chart data pie"),
        new("", "Contrast", "contrast theme"),
        new("", "Map", "map directions navigate"),
        new("", "Bookmark", "bookmark favourite save"),
    };
}
